workspace 'Hello Manticore'

project 'Hello Manticore/Hello Manticore.xcodeproj'

target 'Hello Manticore' do
  platform :ios, '7.0'
  pod 'ManticoreNative', :path => '../../../../', :inhibit_warnings => true
  pod 'ManticoreGenerated', :path => 'generated/', :inhibit_warnings => true
end